# Generated by Django 5.1.1 on 2025-02-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
